---
layout: post
title: Javascript 프로미스
date: 2022-08-19
categories: [Javascript]
tag: [javascript]
---

## **콜백 패턴의 단점**

#### **콜백 헬**

```javascript

    const get = url => {
        const xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.send();

        xhr.onload = () => {
            if (xhr.status === 200) {
                console.log(JSON.parse(xhr.response));
            } else {
                console.error(`${xhr.status} ${xhr.statusText}`);
            }
        };
    };

    get('https://jsonplaceholder.typicode.com/posts/1');

```

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않아도 기다리지 않고 즉시 종료된다. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다. 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

***비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다. 따라서 비동기 함수의 처리 결과에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다. 이런 후속 처리를 위해 콜백 함수를 전달하게 되면서 콜백 헬이 만들어 진다.*** 

```javascript

    const get = (url, callback) => {
        const xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.send();

        xhr.onload = () => {
            if(xhr.status === 200) {
                callback(JSON.parse(xhr.response));
            } else {
                console.error(`${xhr.status} ${xhr.statusText}`);
            }
        };
    };

    const url = 'https://jsonplaceholder.typicode.com';

    // id가 1인 post의 userId를 취득
    get(`${url}/posts/1`, ({ userId }) => {
        console.log(userId);    // 1
        // post의 userId를 사용하여 user 정보를 취득
        get(`${url}/users/${userId}`, userInfo => {
            console.log(userInfo);
        });
    });

```

이러한 콜백 헬은 가독성이 낮아 실수를 유발할 수 있다.

#### **에러 처리**

콜백 패턴에서 가장 큰 문제점은 에러 처리가 곤란하다는 점이다.

```javascript

    try {
        setTimeout(() => { throw new Error('Error!'); }, 1000);
    } catch (e) {
        // 캐치 안됨
        console.error(e);
    }

```

setTimeout 함수의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태다. 이 말은 콜백 함수를 호출한 것이 setTimeout 함수가 아니라는 것을 의미한다. ***에러는 호출자 방향으로 전파된다.*** 따라서 위 코드에서 콜백 함수의 호출자는 setTimeout 함수가 아니며, 에러는 catch 블록에서 캐치되지 않는다.

콜백 패턴에서 문제가되는 콜백 헬과 에러 처리 문제를 극복하기 위해 ES6에서 프로미스가 도입되었다.

## **프로미스 생성**

Promise는 ECMAScript 사양에 정의된 표준 빌트인 객체다. Promise 생성자 함수를 new 연산자와 함께 호출하면 Promise 객체를 생성한다. Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수를 인수로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인수로 전달받는다.

Promise 생성자 함수는 인수로 전달받은 콜백 함수 내부에서 비동기 처리를 수행한다. 이때 비동기 처리가 성공하면 콜백 함수의 인수로 전달받은 resolve 함수를 호출하고, 비동기 처리를 실패하면 reject 함수를 호출한다.

```javascript

    const promiseGet = url => {
        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url);
            xhr.send();

            xhr.onload = () => {
                if(xhr.status === 200) {
                    resolve(JSON.parse(xhr.response));
                } else {
                    reject(new Error(xhr.status));
                }
            };
        });
    };

    promiseGet('https://jsonplaceholder.typicode.com/posts/1');

```

비동기 함수인 promiseGet은 함수 내부에서 프로미스를 생성하고 반환한다. 비동기 처리는 Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행한다. 프로미스는 아래와 같이 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다.

|프로미스의 상태 정보|의미|상태 변경 조건|
|------------------|----|-------------|
|pending|비동기 처리가 아직 수행되지 않는 상태|프로미스가 생성된 직후 기본 상태|
|fulfilled|비동기 처리가 수행된 상태(성공)|resolve 함수 호출|
|fulfilled|비동기 처리가 수행된 상태(실패)|reject 함수 호출|


비동기 처리가 성공하면 프로미스는 pending 상태에서 fulfilled 상태로 변하고 resolve 함수의 결과값을 갖는다. 비동기 처리가 실패하면 프로미스는 pending 상태에서 rejected 상태로 변하고 reject 함수의 결과값을 갖는다. ***프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.***

## **프로미스 후속 처리 메서드**

프로미스는 처리 결과의 후속 처리를 위해 후속 메서드 then, catch, finally를 제공한다. ***프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.*** 이때 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.

#### **Promise.prototype.then**

then 메서드는 두 개의 콜백 함수를 인수로 받는다.

> - 첫 번째 함수는 프로미스가 fulfilled 상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
>
> - 두 번째 함수는 프로미스가 rejected 상태가 되면 호출된다. 이때 콜백 함수는 프로미스의 에러를 인수로 받는다.

```javascript

    // fulfilled
    new Promise(resolve => resolve('fulfilled'))
    .then(v => console.log(v), e => console.error(e));

    // rejected
    new Promise((_, reject) => reject(new Error('rejected')))
    .then(v => console.log(v), e => console.error(e));

```

then 메서드는 언제나 프로미스를 반환한다. then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환하고, 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject하여 프로미스를 생성해 반환한다.

#### **Promise.prototype.catch**

catch 메서드는 한 개의 콜백 함수를 인수로 전달받는다. catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출한다.

```javascript

    // rejected
    new Promise((_, reject) => reject(new Error('rejected')))
    .catch(e => console.log(e));

```

catch 메서드는 then(undefined. onRejected)과 동일하게 동작한다. 따라서 언제나 프로미스를 반환한다.

#### **Promise.prototype.finally**

finally 메서드는 한 개의 콜백 함수를 인수로 전달받는다. finally 메서드의 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다. finally 메서드는 프로미스의 상태와 상관없이 공톡적으로 수행해야 할 처리가 있을 때 유용하다. finally 메서드도 언제나 프로미스를 반환한다.

```javascript

    const promiseGet = url => {
        return new Promise((resolve, reject) => {
            const xhr = new XMLHttpRequest();
            xhr.open('GET', url);
            xhr.send();

            xhr.onload = () => {
                if(xhr.status === 200) {
                    resolve(JSON.parse(xhr.response));
                } else {
                    reject(new Error(xhr.status));
                }
            };
        });
    };

    promiseGet('https://jsonplaceholder.typicode.com/posts/1')
    .then(res => console.log(res))
    .catch(err => console.error(err))
    .finally(() => console.log('Bye'));

```

## **프로미스 에러 처리**

프로미스는 then 메서드의 두 번째 콜백 함수와 catch 메서드를 통해서 에러를 처리할 수 있다.

```javascript

    // then 메서드의 두 번째 콜백 함수를 통한 에러 처리
    promiseGet(wrongUrl).then(
        res => console.log(res),
        err => console.error(err)
    );

    // catch 메서드를 통한 에러 처리
    promiseGet(wrongUrl)
    .then(res => console.log(res))
    .catch(err => console.error(err));

```

단, then 메서드의 두 번째 콜백 함수는 첫 번쨰 콜백 함수에서 발생한 에러를 캐치하지 못하고 코드의 가독성이 떨어진다. 따라서 에러 처리는 catch 메서드에서 처리하는 것이 권장된다.

## **프로미스 체이닝**

```javascript

    const url = 'https://jsonplaceholder.typicode.com';

    promiseGet(`${url}/posts/1`)
    .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
    .then(userInfo => console.log(userInfo))
    .catch(err => console.error(err));

```

then, catch, finally 메서드는 언제나 프로미스를 반환하므로 연속적으로 호출할 수 있다. 이것을 프로미스 체이닝이라 한다. 프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다.

## **프로미스의 정적 메서드**

#### **Promise.resolve/Promise.reject**

Promise.resolve/Promise.reject 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다. 

#### **Promise.all**

Promise.all 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

```javascript

    const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
    const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
    const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

    Promise.all[requestData1(), requestData2(), requestData3()]
    .then(console.log)      // [1, 2, 3] 
    .catch(console.error);

```

Promise.all 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 전달받은 모든 프로미스가 fulfilled 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다. 따라서 Promise.all 메서드를 종료하는데 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 프로미스가 처리되는 시간이다. 

Promise.all 메서드는 어떤 프로미스가 먼저 fulfilled 상태가 되는지와 관계없이 순서가 보장된다. 

Promise.all 메서드는 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료된다.

#### **Promise.race**

Promise.race는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. Promise.all과 차이점은 Promise.all 메서드처럼 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve하는 새로운 프로미스를 반환한다.

```javascript

    const requestData1 = () => new Promise(resolve => setTimeout(() => resolve(1), 3000));
    const requestData2 = () => new Promise(resolve => setTimeout(() => resolve(2), 2000));
    const requestData3 = () => new Promise(resolve => setTimeout(() => resolve(3), 1000));

    Promise.race[requestData1(), requestData2(), requestData3()]
    .then(console.log)      // 3 
    .catch(console.error);

```

#### **Promise.allSettled**

Promise.allSetteled 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받은다. Promise.all과 달리 fulfilled 또는 rejected 상태와 관계없이 모든 프로미스들의 처리 결과를 모두 담아 반환한다.

```javascript

    Promise.allSetteled([
        new Promise(resolve => setTimeout(() => resolve(1), 2000)),
        new Promise((_, reject) => setTimeout(() => reject(new Error('Error')), 1000))
    ]).then(console.log);

    /*
    [
        {status: "fulfilled", value: 1},
        {status: "rejected", reason: Error: Error}
    ]
    */

```

프로미스가 fulfilled 상태인 경우에는 status 와 value 프로퍼티를 갖는다. 프로미가 rejected 상태인 경우에는 status 와 reason 프로퍼티를 갖는다.

## **마이크로태스크 큐**

```javascript

    setTimeout(() => console.log(1), 0);

    Promise.resolve()
    .then(() => console.log(2))
    .then(() => console.log(3));

```

위 코드를 실행하면 1 > 2 > 3 이 출력될 것으로 보이지만 실제로는 2 > 3 > 1 이 출력된다. 그 이유는 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장되기 때문이다. 

마이크로태스크 큐에는 프로미스의 후속 처리 메서드의 콜백 함수가 일시 저장된다. 그 외 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다. ***마이크로태스크 큐는 태스크 큐보다 우선순위가 높다. 즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 실행한다.***

## **fetch**

fetch 함수는 XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다. fetch 함수는 XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

fetch 함수는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다. ***fetch 함수는 HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.***

```javascript

    fetch('https://jsonplaceholder.typicode.com/todos/1')
    // response는 HTTP 응답을 나타내는 Response 객체
    // json 메서드를 사용해서 역직렬화
    .then(response => response.json())
    .then(json => console.log(json));

```

fetch 함수에서는 에러 처리에 주의해야 한다.

```javascript

    fetch(wrongUrl)
    .then(() => console.log('ok'))
    .catch(() => console.log('error'));

```

위 코드를 실행하면 'ok'가 출력된다. ***fetch 함수가 반환하는 프로미스는 기본적으로 404, 500 에러가 발생해도 에러를 reject하지 않고 불리언 타입의 ok 상태를 false로 설정한 Response 객체를 resolve 한다. 오프라인 등의 네트워크 장애나 CROS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject 한다.***

따라서 fetch 함수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해서 명시적으로 에러를 처리해야 한다.

```javascript

    fetch(wrongUrl)
    .then(response => {
        if(!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todo => console.log(todo))
    .catch(err => console.error(err));

```

axios는 클라이언트 단에서 서버에 요청을 보내기 위해 사용하는 비동기 통신 라이브러리로 fetch와 다르게 모든 HTTP 에러를 reject하는 프로미스를 반환한다. 따라서 모든 에러를 catch로 처리할 수 있어 편리하다. axios와 fetch를 상황에 맞게 잘 활용하자.

- GET 요청

```javascript

    request.get('https://jsonplaceholder.typicode.com/todos/1')
    .then(response => {
        if(!request.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));

```

- POST 요청

```javascript

    request.post('https://jsonplaceholder.typicode.com/todos', {
        userId: 1,
        title: 'JS',
        completed: false
    })
    .then(response => {
        if(!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));

```

- PATCH 요청

```javascript

    request.patch('https://jsonplaceholder.typicode.com/todos/1', {
        completed: true
    })
    .then(response => {
        if(!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));

```

- DELETE 요청

```javascript

    request.delete('https://jsonplaceholder.typicode.com/todos/1')
    .then(response => {
        if(!response.ok) throw new Error(response.statusText);
        return response.json();
    })
    .then(todos => console.log(todos))
    .catch(err => console.error(err));

```